apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: api-app-plan
spec:
  params:
  - description: 3Scale URL.
    name: remote
    type: string
  - default: ""
    description: Account ID
    name: account
    type: string
  - description: 3Scale remote name.
    name: remote
    type: string
  - default: "example"
    description: Service System name
    name: service-system-name
    type: string
  - default: ''
    description: Service name
    name: service-name
    type: string    
  - description: 3Scale URL.
    name: base-url
    type: string
  - default: ""
    description: Application Plan name
    name: app-plan-name
    type: string
  - default: "true"
    description: Debug script
    name: verbose
    type: string     
  steps:
    - image: 'registry.redhat.io/3scale-amp2/toolbox-rhel7:3scale2.10'
      name: app-plan-apply
      script: |
        #!/usr/bin/env sh
        
        set -eu

        # Fix 3scale-toolbox image error        
        export BUNDLE_GEMFILE=/opt/toolbox/Gemfile 
        
        SERVICE=`3scale -c /config/.3scalerc.yaml service show $(params.remote) $(params.service-system-name) | awk printf${1} | tail -n +2`

        echo "service = $SERVICE"

        3scale -c /config/.3scalerc.yaml application-plan apply $(params.remote) $SERVICE --name=$(params.app-plan-name) --approval-required=false --enabled=true


      volumeMounts:
        - mountPath: /config
          name: toolbox
      workingDir: /config
  volumes:
    - configMap:
        name: toolbox
      name: toolbox
  workspaces:
  - description: The git repo will be cloned onto the volume backing this Workspace.
    name: shared
   