apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: api-apply-app
spec:
  params:
  - description: 3Scale URL.
    name: remote
    type: string    
  - default: "demo"
    description: Application plan name
    name: app-plan-name
    type: string
  - default: "demo"
    description: Application name
    name: app-name
    type: string    
  - default: "demo"
    description: Application Description
    name: app-description
    type: string    
  - description: 3Scale account.
    name: account
    type: string
  - default: ""
    description: Service System name
    name: toolbox-file
    type: string
  - default: ""
    description: Service ID
    name: service-id
    type: string
  - default: "true"
    description: Debug script
    name: params.verbose
    type: string     
  steps:
    - image: 'registry.redhat.io/3scale-amp2/toolbox-rhel7:3scale2.10'
      name: api-apply-app
      resources: {}      
      script: |
        #!/usr/bin/env sh
        
        set -eu

        if [ "${params.verbose}" = "true" ] ; then
          set -x
        fi

        # Fix 3scale-toolbox image error        
        export BUNDLE_GEMFILE=/opt/toolbox/Gemfile 

        3scale -c /config/.3scalerc.yaml application apply $(params.remote) $(params.app-name) $(params.service-id) --name=$(params.app-name) --service=$(params.service-id) --plan=$(params.app-plan-name) --description=$(params.app-description) --account=$(params.account)

      volumeMounts:
        - mountPath: /config
          name: toolbox
      workingDir: /config
  volumes:
    - configMap:
        name: toolbox
      name: toolbox