apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: api-promote
spec:
  steps:
    - image: 'nmasse/3scale-toolbox:master'
      name: api-promote
      resources: {}
      script: |
        #!/usr/bin/env sh
        set -eu
        3scale -c /config/.3scalerc.yaml proxy-config promote demo demo
      volumeMounts:
        - mountPath: /config
          name: toolbox
      workingDir: /config
  volumes:
    - configMap:
        name: toolbox
      name: toolbox