apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: api-promote
spec:
  params:
  - description: 3Scale URL.
    name: remote
    type: string
  - default: ""
    description: Service System name
    name: service-system-name
    type: string
  - description: 3Scale URL.
    name: remote
    type: string
  - default: ""
    description: Service System name
    name: prod-url
    type: string
  - description: 3Scale URL.
    name: base-url
    type: string
  - default: "example"
    description: Service System name
    name: service-system-name
    type: string
  - default: "true"
    description: Debug script
    name: verbose
    type: string    
  steps:
    - image: 'registry.redhat.io/3scale-amp2/toolbox-rhel7:3scale2.10'
      name: api-promote
      script: |
        #!/usr/bin/env sh
        set -eu
        
        if [ "${params.verbose}" = "true" ] ; then
          set -x
        fi

        # Fix 3scale-toolbox image error        
        export BUNDLE_GEMFILE=/opt/toolbox/Gemfile  

        SERVICE=`3scale -c /config/.3scalerc.yaml service show $(params.remote) $(params.service-system-name) | awk printf${1} | tail -n +2`

        3scale -c /config/.3scalerc.yaml proxy-config promote $(params.remote) $SERVICE

      volumeMounts:
        - mountPath: /config
          name: toolbox
      workingDir: /config
  volumes:
    - configMap:
        name: toolbox
      name: toolbox