apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-pr
  namespace: example
  labels:
    tekton.dev/pipeline: demo
spec:
  params:
    - name: remote
      value: saas
    - name: service-system-name
      value: example
    - name: app-plan-system-name
      value: example
    - name: app-system-name
      value: example
    - name: stage-url
      value: 'http://halting-shock.demo.svc:8080'
    - name: base-url
      value: 'http://halting-shock.demo.svc:8080'
    - name: swager-file
      value: swagger.yaml
    - name: prod-url
      value: 'http://halting-shock-git-demo.apps.cluster-4tdh2.4tdh2.sandbox1123.opentlc.com'
  pipelineRef:
    name: demo
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: gp2
          volumeMode: Filesystem    
